server:
  port: 8080


spring:
  datasource:
    url:   jdbc:mysql://localhost:3306/oa?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: 123456

    